on: [workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
        python3 py/pyneapple_objc.py    
    - if: always()
      run: |
        make hello && ./hello
        make testcall && ./testcall
        # make translated && ./translated
