on: [workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 1
    steps:
    - uses: actions/checkout@v4
    - run: |
        python3 -m py.run
    - if: always()
      run: |
        make hello && ./hello
        make testcall && ./testcall
        # make translated && ./translated
