name: Build&test

on: [workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: bld
      run: |
        clang -Wall -framework Foundation -isysroot `xcrun --show-sdk-path` decl.m -o main
    - run: |
        ./main
