on: [workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
        make hello && ./hello
        # make translated && ./translated
    - run: |
        python3 py/pyneapple_objc.py
