on: [workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 1
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v6
      with:
        python-version: '3.9'
    - run: |
        python -m py.run
    - if: always()
      run: |
        make hello && ./hello
        # make translated && ./translated
