on: [workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
        clang -Wall hello.c -o hello && ./hello
        clang -Wall -framework Foundation -isysroot `xcrun --show-sdk-path` fdn.m -o fdn && otool -L fdn
