on: [workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
        # -c for objects
        clang++ -Wall config.cpp -c -o config.o
        clang -Wall hello.c config.o -o hello
        ./hello
        # clang -Wall hello.c -o hello && ./hello
        # clang -Wall -framework Foundation -isysroot `xcrun --show-sdk-path` fdn.m -o fdn && otool -L fdn
